### ISSUE TITLE
Windows 10 PC run this game, extremely slow

### ISSUE THREAD

**Issue by TenderIronh** [OpenDiablo2/OpenDiablo2#1143]
**Describe the bug**
Windows env. run `go build`, game started and load mpq, extremely slow

**To Reproduce**
1. `go build`, game started and load mpq, extremely slow

**Expected behavior**
Cost 3GB memory and still very slow. The native version could run on 128MB memory PC

**Screenshots**
![图片](https://user-images.githubusercontent.com/89245779/145982892-e89ffc7c-9f03-4bc4-96f4-25186eb8c844.png)

![图片](https://user-images.githubusercontent.com/89245779/145982948-0fe0dba9-77b2-4fce-85de-ca6b0abb2b04.png)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Version [10]

**Additional context**

**Comment by essial** [comment]
Per the main page, this project is no longer in development due to many issues with Golang. The engine has been moved to a c++ core with Lua for the client logic. Now, instead of 3.4gigs of ram, it runs on about 130 megs of ram, and a much lower amount of CPU usage. You can see the project here:

https://github.com/AbyssEngine/AbyssEngine
https://github.com/AbyssEngine/OpenDiablo2

Also check us out on discord (same discord link).
