### ISSUE TITLE
Game Resolution

### ISSUE THREAD

**Issue by arcanis** [OpenDiablo2/OpenDiablo2#435]
**Is your feature request related to a problem? Please describe.**
Diablo II is usually very low resolution. Mods like D2MultiRes exist, but they make the gameplay worse because it becomes possible to attack foes before we enter they line of sight. As a result, mods like Median XL Sigma aren't compatible with it.

**Describe the solution you'd like**
I'd like to have various choices of resolution, and the enemy line of sight to change accordingly.

**Comment by essial** [comment]
I completely agree, but that will be in another phase of the project. The first phase is to faithfully re-create Diablo 2. Once that is done, then we will move the diablo 2 specific logic out into a project to turn this into a more generic engine. At that point things like dynamic resolution and such can be added. Since this is most likely over a yer away I'm going to close this issue, but do know this is absolutely on the long term roadmap. Thanks for the report!
