### ISSUE TITLE
Show Life/Mana when hovering over the life/mana orbs

### ISSUE THREAD

**Issue by gravestench** [OpenDiablo2/OpenDiablo2#687]
When hovering over the life or mana orbs the current and maximum should be displayed, like this:
`Life: X / Y`
`Mana: X / Y`

The strings for "Life" and "Mana" will likely come from the string tables.

**Comment by thetogi** [comment]
I'll take this one.

**Comment by gravestench** [comment]
#750 addresses this

**Comment by leahiel** [comment]
In #750 I hardcoded each of the string tags when they should have used the string lookup table.  I didn't realize OpenD2 had one, and to be fair, it is a little archaic since it is pulled from D2 assets.

Assuming #750 gets merged, I will implement the proper string lookup table stuff into a pull request within a few days.

**Comment by leahiel** [comment]
#751 addresses the hardcoded string issue, among other hardcoded string issues in the panel.

**Comment by leahiel** [comment]
![globehover](https://user-images.githubusercontent.com/71794961/94302244-e77a6b80-ff39-11ea-8513-691914663137.gif)
Issue fully resolved and working.

**Comment by gravestench** [comment]
@leahiel Good work!
