### ISSUE TITLE
Diablo II + Linux

### ISSUE THREAD

**Issue by freesoul** [OpenDiablo2/OpenDiablo2#772]
Hello, I would like to participate to the project, as I am very fan of D2, and always wanted to code a game like this.

The problem I find is I'm not sure how this project is dependent on Diablo II original install. Is it mandatory to have it? 
If so, how am I supossed to have it on Linux, installing it on Windows and moving the files to my Linux distribution?

A bit more of info in the Readme would be super, thank you!

**Comment by ThomasChr** [comment]
Hi freesoul, 

great that you are here!
You are free to change the readme and make it better if anything is unclear to you!

The problem we're facing here is a legal one: It is allowed to make a game engine (from scratch!) which does exactly the same as the original game engine from Diablo. BUT it's not allowed to simply add the assets from Blizzard to it. By assets I mean all of the graphics, the sounds, the videos, the artwork from the original Diablo 2.
(the Devilution Project which reverse enginnered the original Diablo (Version 1, so to speak) faced the same problem and has the same solution:
You need to have the original Disc to play it.

So you have two options: 
1. Diablo 2 runs fine under wine. Install it and Open Diablo 2 can find and use its assets without a problem.
(note: You need to install Diablo 2, Diablo 2 Hellfire, and the most recet Hellfire Patch which is still downloadable here: https://diablo3.ingame.de/diablo-2/patches/#114d )

2. You just copy all MPQ Files (these are packed assets) from the original Diablo 2 Discs to you Computer and configure the paths from Open Diablo 2 in it's config.json so that it will find these files. (Don't forget the MPQ Files from the patch!)
Normally it assumes the location '/home/user/.wine/drive_c/Program Files (x86)/Diablo II' (out of my head, so it can be not exactly right...)

A solution to this problem (and I'm sure this will be the solution we're choosing in the future when Open Diablo 2 is 'ready') would be that Open Diablo 2 justs asks for the discs and the target location for the mpq-Files and copys them for you.
(kind of an installer!)

If you want, I'm sure you can code such an installer. The folks here are happy for everyone who helps.

Do you have any further questions?

Thomas

**Comment by essial** [comment]
Technically it's not mandatory to have the original files, but there's nothing this engine can do without files, and it assumes the files from the D2/LOD installation, so there's not much use in using this without those files -- CURRENTLY. This will change in the future though!
